version: '3'
services:
  user_management_db:
    container_name: user_management_db
    image: postgres
    restart: always
    ports:
      - 5001:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_management_db
    
  auth_db:
    container_name: auth_db
    image: postgres
    restart: always
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db

  user_management_pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: asdf
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - user_management_db
      - auth_db