version: '3'
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: asdf
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80