version: '3'
services:
  auth_db:
    container_name: auth_db
    image: postgres
    restart: always
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db